# Generated by Django 2.2 on 2019-04-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodityinfo', '0001_initial'),
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, verbose_name='商品编号')),
                ('order_detail', models.TextField(verbose_name='订单详情')),
                ('address_name', models.CharField(max_length=30, verbose_name='收件人姓名')),
                ('address_phone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('address', models.CharField(max_length=300, verbose_name='地址')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('acot', models.IntegerField(verbose_name='总数')),
                ('acount', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='总价')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '订单取消')], default=1, verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodityinfo.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='cart_count', verbose_name='数量')),
                ('good', models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='commodityinfo.Goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
        ),
    ]
