# Generated by Django 2.2 on 2019-04-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='用户名')),
                ('upassword', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('isban', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50, verbose_name='收货人')),
                ('address', models.CharField(max_length=300, verbose_name='收获地址')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
        ),
    ]
