# Generated by Django 2.2 on 2019-04-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='分类名称')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='价格')),
                ('picture', models.ImageField(default='normal.png', upload_to='category', verbose_name='商品图片')),
                ('detail', models.TextField(blank=True, default='商品详情', verbose_name='商品详情')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodityinfo.GoodsType')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
